# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{model_set}
  s.version = "0.11.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Balthrop"]
  s.date = %q{2010-04-13}
  s.description = %q{Easy manipulation of sets of ActiveRecord models}
  s.email = %q{code@justinbalthrop.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION.yml",
     "lib/model_set.rb",
     "lib/model_set/conditioned.rb",
     "lib/model_set/conditions.rb",
     "lib/model_set/query.rb",
     "lib/model_set/raw_query.rb",
     "lib/model_set/raw_sql_query.rb",
     "lib/model_set/set_query.rb",
     "lib/model_set/solr_query.rb",
     "lib/model_set/sphinx_query.rb",
     "lib/model_set/sql_base_query.rb",
     "lib/model_set/sql_query.rb",
     "lib/multi_set.rb",
     "model_set.gemspec",
     "test/model_set_test.rb",
     "test/multi_set_test.rb",
     "test/test_helper.rb",
     "vendor/sphinx_client/README.rdoc",
     "vendor/sphinx_client/Rakefile",
     "vendor/sphinx_client/init.rb",
     "vendor/sphinx_client/install.rb",
     "vendor/sphinx_client/lib/sphinx.rb",
     "vendor/sphinx_client/lib/sphinx/client.rb",
     "vendor/sphinx_client/lib/sphinx/request.rb",
     "vendor/sphinx_client/lib/sphinx/response.rb",
     "vendor/sphinx_client/spec/client_response_spec.rb",
     "vendor/sphinx_client/spec/client_spec.rb",
     "vendor/sphinx_client/spec/fixtures/default_search.php",
     "vendor/sphinx_client/spec/fixtures/default_search_index.php",
     "vendor/sphinx_client/spec/fixtures/excerpt_custom.php",
     "vendor/sphinx_client/spec/fixtures/excerpt_default.php",
     "vendor/sphinx_client/spec/fixtures/excerpt_flags.php",
     "vendor/sphinx_client/spec/fixtures/field_weights.php",
     "vendor/sphinx_client/spec/fixtures/filter.php",
     "vendor/sphinx_client/spec/fixtures/filter_exclude.php",
     "vendor/sphinx_client/spec/fixtures/filter_float_range.php",
     "vendor/sphinx_client/spec/fixtures/filter_float_range_exclude.php",
     "vendor/sphinx_client/spec/fixtures/filter_range.php",
     "vendor/sphinx_client/spec/fixtures/filter_range_exclude.php",
     "vendor/sphinx_client/spec/fixtures/filter_range_int64.php",
     "vendor/sphinx_client/spec/fixtures/filter_ranges.php",
     "vendor/sphinx_client/spec/fixtures/filters.php",
     "vendor/sphinx_client/spec/fixtures/filters_different.php",
     "vendor/sphinx_client/spec/fixtures/geo_anchor.php",
     "vendor/sphinx_client/spec/fixtures/group_by_attr.php",
     "vendor/sphinx_client/spec/fixtures/group_by_attrpair.php",
     "vendor/sphinx_client/spec/fixtures/group_by_day.php",
     "vendor/sphinx_client/spec/fixtures/group_by_day_sort.php",
     "vendor/sphinx_client/spec/fixtures/group_by_month.php",
     "vendor/sphinx_client/spec/fixtures/group_by_week.php",
     "vendor/sphinx_client/spec/fixtures/group_by_year.php",
     "vendor/sphinx_client/spec/fixtures/group_distinct.php",
     "vendor/sphinx_client/spec/fixtures/id_range.php",
     "vendor/sphinx_client/spec/fixtures/id_range64.php",
     "vendor/sphinx_client/spec/fixtures/index_weights.php",
     "vendor/sphinx_client/spec/fixtures/keywords.php",
     "vendor/sphinx_client/spec/fixtures/limits.php",
     "vendor/sphinx_client/spec/fixtures/limits_cutoff.php",
     "vendor/sphinx_client/spec/fixtures/limits_max.php",
     "vendor/sphinx_client/spec/fixtures/limits_max_cutoff.php",
     "vendor/sphinx_client/spec/fixtures/match_all.php",
     "vendor/sphinx_client/spec/fixtures/match_any.php",
     "vendor/sphinx_client/spec/fixtures/match_boolean.php",
     "vendor/sphinx_client/spec/fixtures/match_extended.php",
     "vendor/sphinx_client/spec/fixtures/match_extended2.php",
     "vendor/sphinx_client/spec/fixtures/match_fullscan.php",
     "vendor/sphinx_client/spec/fixtures/match_phrase.php",
     "vendor/sphinx_client/spec/fixtures/max_query_time.php",
     "vendor/sphinx_client/spec/fixtures/miltiple_queries.php",
     "vendor/sphinx_client/spec/fixtures/ranking_bm25.php",
     "vendor/sphinx_client/spec/fixtures/ranking_none.php",
     "vendor/sphinx_client/spec/fixtures/ranking_proximity.php",
     "vendor/sphinx_client/spec/fixtures/ranking_proximity_bm25.php",
     "vendor/sphinx_client/spec/fixtures/ranking_wordcount.php",
     "vendor/sphinx_client/spec/fixtures/retries.php",
     "vendor/sphinx_client/spec/fixtures/retries_delay.php",
     "vendor/sphinx_client/spec/fixtures/select.php",
     "vendor/sphinx_client/spec/fixtures/set_override.php",
     "vendor/sphinx_client/spec/fixtures/sort_attr_asc.php",
     "vendor/sphinx_client/spec/fixtures/sort_attr_desc.php",
     "vendor/sphinx_client/spec/fixtures/sort_expr.php",
     "vendor/sphinx_client/spec/fixtures/sort_extended.php",
     "vendor/sphinx_client/spec/fixtures/sort_relevance.php",
     "vendor/sphinx_client/spec/fixtures/sort_time_segments.php",
     "vendor/sphinx_client/spec/fixtures/sphinxapi.php",
     "vendor/sphinx_client/spec/fixtures/update_attributes.php",
     "vendor/sphinx_client/spec/fixtures/update_attributes_mva.php",
     "vendor/sphinx_client/spec/fixtures/weights.php",
     "vendor/sphinx_client/spec/sphinx/sphinx-id64.conf",
     "vendor/sphinx_client/spec/sphinx/sphinx.conf",
     "vendor/sphinx_client/spec/sphinx/sphinx_test.sql",
     "vendor/sphinx_client/sphinx.yml.tpl",
     "vendor/sphinx_client/tasks/sphinx.rake"
  ]
  s.homepage = %q{http://github.com/ninjudd/model_set}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy manipulation of sets of ActiveRecord models}
  s.test_files = [
    "test/model_set_test.rb",
     "test/multi_set_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<ordered_set>, [">= 1.0.0"])
      s.add_runtime_dependency(%q<deep_clonable>, [">= 1.0.2"])
      s.add_runtime_dependency(%q<activerecord>, [">= 2.0.0"])
    else
      s.add_dependency(%q<ordered_set>, [">= 1.0.0"])
      s.add_dependency(%q<deep_clonable>, [">= 1.0.2"])
      s.add_dependency(%q<activerecord>, [">= 2.0.0"])
    end
  else
    s.add_dependency(%q<ordered_set>, [">= 1.0.0"])
    s.add_dependency(%q<deep_clonable>, [">= 1.0.2"])
    s.add_dependency(%q<activerecord>, [">= 2.0.0"])
  end
end

